# Generated by Django 3.0.2 on 2020-01-23 21:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('GameLibrary', '0002_auto_20200123_2045'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='price',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='game', to='GameLibrary.Price'),
        ),
    ]
